title:              Alex Abades Grimes 
email:              abadesalex31@gmail.com
description:        Welcome to my portfolio
author:             Alex Abades Grimes
baseurl:            "/"
url:                "https://alexabades.github.io"

# Social Profiles
twitter_username:   
github_username:    alexabades
facebook_username:  
instagram_username:  
linkedin_username: alexabades

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
